apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  labels:
    app: $POD_NAME
spec:
    containers:
    - name: container
      image: mbodenhamer/echoserver:latest
      env:
        - name: LISTEN_PORTS
          value: "5001,5002,5003,5004,5005,5006,5007,5008,5009,5010"