apiVersion: v1
kind: Pod
metadata:
  name: $POD_NAME
  labels:
    app: $POD_NAME
spec:
  containers:
  - name: david-container
    image: dfattakhov/multiport-server:latest
    command: ["python3"]
    args: ["/app/app.py"]
    env:
      - name: LISTENING_PORTS
        value: "$PORTS"
